---
  title: "Complete schema: engine.protoc.mermaid.example.hideemptymembersbox"
  config:
    class:
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.hideemptymembersbox {
        class Empty

        class HasFields {
            string id
        }
    }
