---
  title: "Message: engine.protoc.mermaid.example.hideemptymembersbox.Empty"
  config:
    class:
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.hideemptymembersbox {
        class Empty
    }
