---
  title: "Message: engine.protoc.mermaid.example.hideemptymembersbox.HasFields"
  config:
    class:
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.hideemptymembersbox {
        class HasFields {
            string id
        }
    }
