---
  title: "Message: engine.protoc.mermaid.example.hierarchical.Item"
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
    namespace engine.protoc.mermaid.example.hierarchical {
        class Item {
            string id
        }
    }
