---
  title: "Complete schema: engine.protoc.mermaid.example.hierarchical"
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
    namespace engine.protoc.mermaid.example.hierarchical {
        class Item {
            string id
        }
    }
