---
  title: "File overview: hierarchical_namespaces.proto"
  config:
    class:
      hideEmptyMembersBox: true
---
classDiagram
    namespace engine.protoc.mermaid.example.hierarchical {
        class Item {
            string id
        }
    }
