---
  generated-by: https://github.com/hotelengine/protoc-gen-mermaid/releases/tag/0.0.0-pre.0
  protoc-gen-mermaid-generated-on: 2026-01-01T00:00:00Z
  protoc-gen-mermaid-options: hideEmptyMembersBox=true,hierarchicalNamespaces=false,suppressNamespaces=false,suppressVisibility=true,diagramTypes=FILE_OVERVIEW,diagramTypes=MESSAGE,diagramTypes=COMPLETE,diagramTypes=PACKAGE,diagramTypes=SERVICE,diagramTypes=ENUMERATION,oneofRenderingType=SEPARATE,outputType=STANDALONE_MERMAID,fileOverviewInsertionPoint=file_header_scope,messageInsertionPoint=message_header_scope,serviceInsertionPoint=service_header_scope,enumerationInsertionPoint=enum_header_scope,completeInsertionPoint=file_header,packageInsertionPoint=file_header,suppressWellKnownTypes=true,direction=TB
  title: "Complete schema: engine.protoc.mermaid.example.oneof"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.oneof {
        class Choice {
            string id
            Detail detail
        }

        class Choice_selector["Choice.selector"] {
            <<oneof>>
            string by_name
            int32 by_id
        }

        class Detail

        class Detail_kind["Detail.kind"] {
            <<oneof>>
            string note
        }
    }

    Choice --> "0..1" Detail : detail
    Choice *-- "0..1" Choice_selector : selector
    Detail *-- "0..1" Detail_kind : kind
