---
  title: "Message: engine.protoc.mermaid.example.suppressns.Foo"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    class Foo {
        string id
    }
