---
  title: "File overview: suppress_namespaces.proto"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    class Foo {
        string id
    }
