---
  title: "Complete schema: engine.protoc.mermaid.example.suppressns"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    class Foo {
        string id
    }
