---
  title: "Package: engine.protoc.mermaid.example.wkt"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.wkt {
        class Event {
            string id
            Timestamp at
        }
    }

    Event --> "0..1" Timestamp : at
