---
  title: "Complete schema: engine.protoc.mermaid.example.suppressvis"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.suppressvis {
        class Item {
            +string name
            +int32 quantity
        }
    }
