---
  title: "File overview: suppress_visibility.proto"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.suppressvis {
        class Item {
            +string name
            +int32 quantity
        }
    }
