---
  title: "Complete schema: engine.protoc.mermaid.example.hello"
---
classDiagram
    namespace engine.protoc.mermaid.example.hello {
        class Greeting {
            +string text
        }

        class Greeter {
            <<service>>
            SayHello(Greeting) Greeting
        }
    }

    Greeter ..> "1" Greeting : SayHello
    Greeter ..> "1" Greeting : SayHello
