---
  title: "Package: engine.protoc.mermaid.example.pkg.alpha"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.pkg.alpha {
        class Alpha {
            string id
        }
    }
