---
  title: "Complete schema: engine.protoc.mermaid.example.diagramtypes"
  config:
    class:
      hideEmptyMembersBox: true
      hierarchicalNamespaces: false
---
classDiagram
    namespace engine.protoc.mermaid.example.diagramtypes {
        class Alpha {
            string id
        }

        class Beta {
            string id
        }
    }
